apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: httpd:alpine3.19
          name: httpd
          command: ["/bin/bash", "-c"] # Command to run in the container
          args: ["sleep 5; exit 1"] # Sleep for 5 seconds and exit with status code 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
