global:
  scrape_interval: 15s


scrape_configs:
  - job_name      : "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name      : "prod-servers"
    ec2_sd_configs:
    - port: 9100
      filters:
        - name  : tag:Environment
          values: ["prod"]


  - job_name      : "dev-servers"
    ec2_sd_configs:
    - port: 9100
      filters:
        - name  : tag:Environment
          values: ["dev"]
